
insert into Country values (1,'Afghanistan');
insert into Country values (2,'Albania');
insert into Country values (3,'Algeria');
insert into Country values (4,'Andorra');
insert into Country values (5,'Angola');
insert into Country values (6,'Antigua & Deps');
insert into Country values (7,'Argentina');
insert into Country values (8,'Armenia');
insert into Country values (9,'Australia');
insert into Country values (10,'Austria');
insert into Country values (11,'Azerbaijan');
insert into Country values (12,'Bahamas');
insert into Country values (13,'Bahrain');
insert into Country values (14,'Bangladesh');
insert into Country values (15,'Barbados');
insert into Country values (16,'Belarus');
insert into Country values (17,'Belgium');
insert into Country values (18,'Belize');
insert into Country values (19,'Benin');
insert into Country values (20,'Bhutan');
insert into Country values (21,'Bolivia');
insert into Country values (22,'Bosnia Herzegovina');
insert into Country values (23,'Botswana');
insert into Country values (24,'Brazil');
insert into Country values (25,'Brunei');
insert into Country values (26,'Bulgaria');
insert into Country values (27,'Burkina');
insert into Country values (28,'Burundi');
insert into Country values (29,'Cambodia');
insert into Country values (30,'Cameroon');
insert into Country values (31,'Canada');
insert into Country values (32,'Cape Verde');
insert into Country values (33,'Central African Rep');
insert into Country values (34,'Chad');
insert into Country values (35,'Chile');
insert into Country values (36,'China');
insert into Country values (37,'Colombia');
insert into Country values (38,'Comoros');
insert into Country values (39,'Congo');
insert into Country values (40,'Congo {Democratic Rep}');
insert into Country values (41,'Costa Rica');
insert into Country values (42,'Croatia');
insert into Country values (43,'Cuba');
insert into Country values (44,'Cyprus');
insert into Country values (45,'Czech Republic');
insert into Country values (46,'Denmark');
insert into Country values (47,'Djibouti');
insert into Country values (48,'Dominica');
insert into Country values (49,'Dominican Republic');
insert into Country values (50,'East Timor');
insert into Country values (51,'Ecuador');
insert into Country values (52,'Egypt');
insert into Country values (53,'El Salvador');
insert into Country values (54,'Equatorial Guinea');
insert into Country values (55,'Eritrea');
insert into Country values (56,'Estonia');
insert into Country values (57,'Ethiopia');
insert into Country values (58,'Fiji');
insert into Country values (59,'Finland');
insert into Country values (60,'France');
insert into Country values (61,'Gabon');
insert into Country values (62,'Gambia');
insert into Country values (63,'Georgia');
insert into Country values (64,'Germany');
insert into Country values (65,'Ghana');
insert into Country values (66,'Greece');
insert into Country values (67,'Grenada');
insert into Country values (68,'Guatemala');
insert into Country values (69,'Guinea');
insert into Country values (70,'Guinea-Bissau');
insert into Country values (71,'Guyana');
insert into Country values (72,'Haiti');
insert into Country values (73,'Honduras');
insert into Country values (74,'Hungary');
insert into Country values (75,'Iceland');
insert into Country values (76,'India');
insert into Country values (77,'Indonesia');
insert into Country values (78,'Iran');
insert into Country values (79,'Iraq');
insert into Country values (80,'Ireland {Republic}');
insert into Country values (81,'Israel');
insert into Country values (82,'Italy');
insert into Country values (83,'Ivory Coast');
insert into Country values (84,'Jamaica');
insert into Country values (85,'Japan');
insert into Country values (86,'Jordan');
insert into Country values (87,'Kazakhstan');
insert into Country values (88,'Kenya');
insert into Country values (89,'Kiribati');
insert into Country values (90,'Korea North');
insert into Country values (91,'Korea South');
insert into Country values (92,'Kosovo');
insert into Country values (93,'Kuwait');
insert into Country values (94,'Kyrgyzstan');
insert into Country values (95,'Laos');
insert into Country values (96,'Latvia');
insert into Country values (97,'Lebanon');
insert into Country values (98,'Lesotho');
insert into Country values (99,'Liberia');
insert into Country values (100,'Libya');
insert into Country values (101,'Liechtenstein');
insert into Country values (102,'Lithuania');
insert into Country values (103,'Luxembourg');
insert into Country values (104,'Macedonia');
insert into Country values (105,'Madagascar');
insert into Country values (106,'Malawi');
insert into Country values (107,'Malaysia');
insert into Country values (108,'Maldives');
insert into Country values (109,'Mali');
insert into Country values (110,'Malta');
insert into Country values (111,'Marshall Islands');
insert into Country values (112,'Mauritania');
insert into Country values (113,'Mauritius');
insert into Country values (114,'Mexico');
insert into Country values (115,'Micronesia');
insert into Country values (116,'Moldova');
insert into Country values (117,'Monaco');
insert into Country values (118,'Mongolia');
insert into Country values (119,'Montenegro');
insert into Country values (120,'Morocco');
insert into Country values (121,'Mozambique');
insert into Country values (122,'Myanmar, {Burma}');
insert into Country values (123,'Namibia');
insert into Country values (124,'Nauru');
insert into Country values (125,'Nepal');
insert into Country values (126,'Netherlands');
insert into Country values (127,'New Zealand');
insert into Country values (128,'Nicaragua');
insert into Country values (129,'Niger');
insert into Country values (130,'Nigeria');
insert into Country values (131,'Norway');
insert into Country values (132,'Oman');
insert into Country values (133,'Pakistan');
insert into Country values (134,'Palau');
insert into Country values (135,'Panama');
insert into Country values (136,'Papua New Guinea');
insert into Country values (137,'Paraguay');
insert into Country values (138,'Peru');
insert into Country values (139,'Philippines');
insert into Country values (140,'Poland');
insert into Country values (141,'Portugal');
insert into Country values (142,'Qatar');
insert into Country values (143,'Romania');
insert into Country values (144,'Russian Federation');
insert into Country values (145,'Rwanda');
insert into Country values (146,'St Kitts & Nevis');
insert into Country values (147,'St Lucia');
insert into Country values (148,'Saint Vincent & the Grenadines');
insert into Country values (149,'Samoa');
insert into Country values (150,'San Marino');
insert into Country values (151,'Sao Tome & Principe');
insert into Country values (152,'Saudi Arabia');
insert into Country values (153,'Senegal');
insert into Country values (154,'Serbia');
insert into Country values (155,'Seychelles');
insert into Country values (156,'Sierra Leone');
insert into Country values (157,'Singapore');
insert into Country values (158,'Slovakia');
insert into Country values (159,'Slovenia');
insert into Country values (160,'Solomon Islands');
insert into Country values (161,'Somalia');
insert into Country values (162,'South Africa');
insert into Country values (163,'South Sudan');
insert into Country values (164,'Spain');
insert into Country values (165,'Sri Lanka');
insert into Country values (166,'Sudan');
insert into Country values (167,'Suriname');
insert into Country values (168,'Swaziland');
insert into Country values (169,'Sweden');
insert into Country values (170,'Switzerland');
insert into Country values (171,'Syria');
insert into Country values (172,'Taiwan');
insert into Country values (173,'Tajikistan');
insert into Country values (174,'Tanzania');
insert into Country values (175,'Thailand');
insert into Country values (176,'Togo');
insert into Country values (177,'Tonga');
insert into Country values (178,'Trinidad & Tobago');
insert into Country values (179,'Tunisia');
insert into Country values (180,'Turkey');
insert into Country values (181,'Turkmenistan');
insert into Country values (182,'Tuvalu');
insert into Country values (183,'Uganda');
insert into Country values (184,'Ukraine');
insert into Country values (185,'United Arab Emirates');
insert into Country values (186,'United Kingdom');
insert into Country values (187,'United States');
insert into Country values (188,'Uruguay');
insert into Country values (189,'Uzbekistan');
insert into Country values (190,'Vanuatu');
insert into Country values (191,'Vatican City');
insert into Country values (192,'Venezuela');
insert into Country values (193,'Vietnam');
insert into Country values (194,'Yemen');
insert into Country values (195,'Zambia');
insert into Country values (196,'Zimbabwe');


insert into Sport (id, name, image_name, description) values (1,'3x3 Basketball','bk3', '3x3 basketball is an exciting, urban and innovative variation of basketball played with three players on each team on a half-court setup with one hoop and backboard. It is widely held to be the world’s number one urban team sport. 3x3 basketball is an exciting, urban and innovative variation of basketball played with three players on each team on a half-court setup with one hoop and backboard. It is widely held to be the world’s number one urban team sport.');
insert into Sport (id, name, image_name, description) values (2,'Alpine Skiing','alp', 'Skiing has an ancient history. The birth of modern downhill skiing is often dated to the 1850s, when Norwegian legend Sondre Norheim popularised skis with curved sides, bindings with stiff heel bands made of willow, as well as the Telemark and Christiania (slalom) turns. Skiing changed from a method of transportation into a sporting activity during the late 19th century. The first non-military skiing competitions are reported to have been held in the 1840s in northern and central Norway. The first national skiing competition in Norway, held in the capital Christiania (now Oslo) and won by Sondre Norheim, in 1868, is regarded as the beginning of a new era of skiing enthusiasm.');
insert into Sport (id, name, image_name, description) values (3,'Archery','arc', 'Archery is one of the oldest sports still practised, and is closely linked to the development of civilisation. Using bows and arrows, the sport as a history dating back thousands of years. As a cultural advance, it was comparable to the discovery of fire and the invention of the wheel. Archery was the favourite sport of the Egyptian pharaohs during the 18th dynasty (1567-1320 BC). Many centuries later, some of the earliest recorded archery tournaments took place during the Zhou dynasty (1046 - 256 BC) in China. Such events were attended by Chinese nobility. Much later, English writers honoured the longbow for famous contributions to their country’s victories in the battles of Crécy, Agincourt and Poitiers.');
insert into Sport (id, name, image_name, description) values (4,'Artistic Gymnastics','gar', 'Introduced in 1894, artistic gymnastics was one of the original disciplines in the modern Olympic Games. Artistic gymnasts are challenged to perfect their skills across a range of equipment, such as the beam and performing on the floor. The term "artistic gymnastics" emerged in the early 1800s to distinguish free-flowing styles from techniques used in military training. Gymnastic competitions began to flourish in schools and athletic clubs across Europe, and made a fitting return at the first edition of the modern Olympic Games were revived in Athens in 1896.');
insert into Sport (id, name, image_name, description) values (5,'Artistic Swimming','swa', 'Artistic swimming, formerly known as synchronised swimming, is a relatively new discipline with its origins in water acrobatics. Originally known as water ballet, the pastime was first practised in the late 19th century with the first recorded competition held in the German capital Berlin in 1891.');
insert into Sport (id, name, image_name, description) values (6,'Athletics','ath', 'Athletics is a sport that includes a number of events involving running, jumping, throwing or walking. Often referred to as track & field, the sport includes single events, such as the 100m, marathon or long jump, combined events, including the decathlon and heptathlon, or team-based events such as the 4x100m relays. While athletics has been practised throughout history, the first ever event contested at the ancient Olympic Games was the “stadium” race, a sprint of about 192 metres. Winners in this event have been recorded from as far back as 776 BC.');
insert into Sport (id, name, image_name, description) values (7,'Badminton','bdm', 'While athletics has been practised throughout history, the first ever event contested at the ancient Olympic Games was the “stadium” race, a sprint of about 192 metres. Winners in this event have been recorded from as far back as 776 BC. The sport quickly grew in popularity, and in 1877, the first set of written rules were devised by the newly formed Bath Badminton Club. The Badminton Federation of England was created 16 years later, and in 1899, it organised the first All England Championships.');
insert into Sport (id, name, image_name, description) values (8,'Baseball Softball','bsb', 'Baseball and softball are two related ball sports played between two teams on a diamond-shaped field. While there are world championships for both men and women in both sports, at the Olympic level baseball has been a men-only sport while softball has been a women-only sport. There are differences in the number of players on each team between the two sports, the size of the field, and in some rules.');
insert into Sport (id, name, image_name, description) values (9,'Basketball','bkb', 'Basketball is a team sport played on a rectangular court where two opposing teams made up of five players attempt to score by throwing a ball into the hoop of the opponent and net, otherwise known as a basket. Basketball was invented in December 1891 by Canadian James W. Naismith, an instructor at the YMCA Training School in Massachusetts.');
insert into Sport (id, name, image_name, description) values (10,'Beach Handball','hbb', 'In the late 1980s, Italian coach Simonetta Montagni began developing handball on the beach. As the discipline began to grow in popularity, coach Luciano Bartolini was asked to create the first set of rules for the game in 1990, making the fast-paced game fit within the existing beach volleyball court lines. In 2000, beach handball became an official European Handball Federation (EHF) sport, and the first EHF Beach Handball European Championship was held that year in Gaeta, Italy. The sport was further developed with representatives of the International Handball Federation (IHF), and it began to reach a global audience.');
insert into Sport (id, name, image_name, description) values (11,'Beach Volleyball','vbv', 'Olympic beach volleyball is a team sport played by two players on each side of a sand court divided by a net. The objective of the game is to hit the ball – with hands or arms only – over the net into the opponents’ court until the other side is unable to return the ball or the ball heads outside of the court lines. Each rally secures one point. Beach volleyball is a variant of the indoor version, invented in 1895 by American gym teacher William G Morgan.');
insert into Sport (id, name, image_name, description) values (12,'Biathlon','bth', 'Biathlon combines the power and aggression of cross-country skiing with the precision and calm of marksmanship. The word "biathlon" stems from the Greek word for two contests, and is today seen as the joining of two sports: skiing and shooting. Biathlon has its roots in survival skills practised in the snow-covered forests of Scandinavia, where people hunted on skis with rifles slung over their shoulders.');
insert into Sport (id, name, image_name, description) values (13,'Bobsleigh','bob', 'Bobsleigh is a winter sport invented by the Swiss in the late 1860s, in which teams make timed runs down narrow, twisting, banked, iced tracks in a gravity-powered sled. The sport of bobsleigh did not begin until the late 19th century, when the Swiss attached two skeleton sleds together and added a steering mechanism to make a toboggan. A chassis was added to give protection to wealthy tourists, and the world first bobsleigh club was founded in St. Moritz, Switzerland in 1897.');
insert into Sport (id, name, image_name, description) values (14,'Boxing','box', 'Boxing is a form of hand-to-hand unarmed combat where one athlete attempts to land punches on the head or body (above waist-height) of the opponent to score points - as decided by judges - or render said opponent unable to continue. While the earliest evidence of boxing dates back to Ancient Egypt in around 3000 BC, it was not until the 16th century that prizefighting or bare-knuckle boxing began to spring up, largely in Great Britain.');
insert into Sport (id, name, image_name, description) values (15,'Breaking','dan', 'From the streets of New York to the biggest stage in sports: breaking (also known as breakdancing) is an urban dance style that originated in the Bronx borough of New York in the 1970s. It is a form of dance sport that blends urban dance with remarkable athleticism. It emerges from hip hop culture and is characterised by acrobatic movements, Since its start on the streets, breaking has developed and gained a global following as an art form, intertwining elements of music, dance and athleticism. ');
insert into Sport (id, name, image_name, description) values (16,'Canoe Flatwater','csp', 'Canoe sprint sees competitors race each other on a flatwater course over distances between 200 and 1000 metres. There are two types of boats: canoes, where the athlete is strapped into the boat in a kneeling position using a single-blade paddle, and kayaks with the athletes seated and employing a double-bladed paddle.');
insert into Sport (id, name, image_name, description) values (17,'Canoe Slalom','csl', 'Canoe slalom sees competitors navigate a whitewater course - up to 300 metres in length - by passing through a maximum 25 upstream and downstream gates in as quick a time as possible. There are two types of boats: canoes, where the athlete is strapped into the boat in a kneeling position using a single-blade paddle, and kayaks with the athletes seated and employing a double-bladed paddle.');
insert into Sport (id, name, image_name, description) values (18,'Curling','cur', 'Curling is a team sport played by two teams of four players on a rectangular sheet of ice. Its nickname, "the roaring game", originates from the rumbling sound the 44-pound (19.96kg) granite stones make when they travel across the ice.');
insert into Sport (id, name, image_name, description) values (19,'Cross-Country Skiing','ccs', 'Cross-country skiing is the oldest type of skiing. It emerged from a need to travel over snow-covered terrain and developed as a sport at the end of the 19th century. Different types of skis emerged at various regions at about the same time. One type had a horizontal toe-piece binding. The modern ski bindings are based on the Fennoscandian model of the 19th century. The East-Siberian type was a thin board with a vertical four-hole binding. Sometimes it was covered with fur. The Lapps used a horizontal stem-hole binding. Present-day cross-country skis were developed from the type used by the Lapps.');
insert into Sport (id, name, image_name, description) values (20,'Cycling BMX Freestyle','bmf', 'In BMX Freestyle, riders perform routines consisting of sequences of tricks carried out on flat ground, in the streets, on dirt jumps, a halfpipe and/or on constructed ramps. In competition, riders are judged on the quality of their performance. Bicycle Motocross (BMX) Freestyle quickly developed as a separate discipline from BMX Racing following its start in the 1960s in California.From 1980 until 1987, BMX Freestyle increased in popularity. The discipline’s founding governing body was first called the Amateur Skate Park Association (ASPA) in 1982, and then a couple years after, it changed to the American Freestyle Association (AFA). Eventually, the discipline became governed by the Union Cycliste Internationale (UCI).');
insert into Sport (id, name, image_name, description) values (21,'Cycling BMX Racing','bmx', 'BMX racing involves up to eight BMX cyclists competing on a single-lap track with straights, jumps and turns. The first across the finish line wins the race. Bicycle motocross (BMX) started in the late 1960s in California, around the time that motocross became a popular sport in the USA. The motorised version of the sport was the inspiration for the human-powered competition. BMX racing offered exciting action at a low cost, and the infant sport became an instant hit, especially in California. This led to the foundation of a sanctioning body for BMX in the USA in the early 1970s. ');
insert into Sport (id, name, image_name, description) values (22,'Cycling Mountain Bike','mtb', 'In the 1970s, mountain biking developed as a fringe sport in California. Taking a bike off-road was nothing new, but the development of a new bike that relished such terrain was; these bikes had fatter tyres, rapid-shift gears, drum brakes and ground-breaking suspension. These bikes gave thrill-seeking cyclists much more freedom, and the sport of mountain biking was born.');
insert into Sport (id, name, image_name, description) values (23,'Cycling Road','crd', 'Road cycling involves mass races or time trials raced on usually paved roads, although sometimes also over cobblestones or very occasionally gravel roads. In 1885, cycling took a big leap forward when J.K. Starley devised the chain-and-gearing system. Since then, engineers have embraced modern technology to build ever faster, sleeker and lighter bikes.');
insert into Sport (id, name, image_name, description) values (24,'Cycling Track','ctr', 'Track cycling involves races on bikes set on an oval track, often made of wood and usually indoors but not always, in a velodrome. As early as 1870, track races in England were regularly attracting large crowds. The riders competed on wooden indoor tracks that closely resembled the modern velodromes of today. Such tracks ensured the event could be competed all year round. But for promoters, there was an even greater benefit—spectators could be charged an entrance fee.');
insert into Sport (id, name, image_name, description) values (25,'Diving','div', 'Diving is a sport where athletes jump or fall into water from a platform or springboard while performing acrobatic routines. The sport of diving became popular in Sweden and Germany in the 18th and 19th centuries, and was primarily practised by gymnasts who started performing tumbling routines into the water.');
insert into Sport (id, name, image_name, description) values (26,'Equestrian','equ', 'Equestrian is the broad umbrella term for sport involving riding on horseback. There are numerous equestrian disciplines ranging from horse racing and vaulting (gymnastics on horseback) to polo and rodeo. There are three disciplines in the Olympic Games: dressage, eventing, and jumping (also known as show jumping).');
insert into Sport (id, name, image_name, description) values (27,'Fencing','fen', 'Fencing is a combat sport in which two athletes use swords to attack and defend against one another with the aim of striking their opponent in order to score points. Evidence of sword fights goes back as far as Ancient Egypt in 1190 BC with bouts and duels continuing until the 18th century.');
insert into Sport (id, name, image_name, description) values (28,'Figure Skating','fsk', 'Figure skating, as its name suggests, involves skating "figures" on ice. The sport requires competitors to skate selected patterns, or figures, as part of their routines. Ice skating has developed from a practical way to get around on ice into the elegant mix of art and sport it is today. The Dutch were arguably the earliest pioneers of skating. They began using canals to maintain communication by skating from village to village as far back as the 13th century. Skating eventually spread across the channel to England, and soon the first clubs and artificial rinks began to form. Passionate skaters included several kings of England, Marie Antoinette, Napoleon III and German writer Johann Wolfgang von Goethe.');
insert into Sport (id, name, image_name, description) values (29,'Football','fbl', 'Football is the most popular sport in the world and sees opposing teams of 11 players try to score goals primarily by use of the feet. Football has its roots in ancient China while the modern version of the game began on the streets of medieval England. Neighbouring towns would play each other in games where a heaving mass of players would struggle to drag a pig’s bladder by any means possible to markers at either end of town.');
insert into Sport (id, name, image_name, description) values (30,'Freestyle Skiing','frs', 'Freestyle skiing combines speed, showmanship and the ability to perform aerial manoeuvres whilst skiing. There are records of people performing somersaults on skis at the beginning of the 20th century in Norway, Italy and Austria, and in the early 1920s, U.S. skiers started to flip and spin. Freestyle skiing really began to take off in America during the 1960s, when social change and freedom of expression together with the advances in ski equipment led to the development of new and exciting skiing techniques. Freestyle skiing was affectionately known as ‘hotdogging’. The name seemed to perfectly capture the breathtaking mix of acrobatic tricks, jumps and sheer adrenalin rush of the sport.');
insert into Sport (id, name, image_name, description) values (31,'Futsal','fut', 'Futsal, commonly translated as “indoor football”, comes from the Spanish “fútbol sala” and from the Portuguese “futebol de salão”. Futsal is a five-a-side format of football, and the only form of indoor football approved by world governing body FIFA. Futsal emphasises technique, creativity, improvisation and ball control.');
insert into Sport (id, name, image_name, description) values (32,'Golf','glf', 'Golf is a sport where the idea is to hit a ball with a club from the tee into the hole in as few strokes as possible. Golf is believed to have been practised first in the Netherlands under the name “colf” or “kolven” and arrived in Britain in the 15th century. Its first rules were established in the Scottish city of St. Andrews, long known as the home of golf, in 1754s');
insert into Sport (id, name, image_name, description) values (33,'Handball','hbl', 'Handball is a fast-paced indoor game where opposing teams try to score by throwing a ball into a football-style goal with posts and a crossbar. Handball was first played towards the end of the 19th century in Scandinavia and Germany. Field handball - an 11-a-side game played outdoors - was first recognised at the turn of the century, and G. Wallström introduced indoor handball to Sweden in 1910.');
insert into Sport (id, name, image_name, description) values (34,'Hockey','hoc', 'There are two types of hockey – field and ice. Field hockey, played at the Olympic Summer Games, takes place on an artificial-grass pitch where two teams of 11 – 10 infield players and one goalkeeper – compete against each other to score the most goals in the opposing side’s net. Players use a stick with a rounded end to hit a hard ball, slightly larger than a tennis ball. A form of hockey has been played in various guises for thousands of years – in Egypt (4,000 years ago), Ethiopia (1,000 BC), and Iran (2,000 BC).');
insert into Sport (id, name, image_name, description) values (35,'Ice Hockey','iho', 'Ice hockey is a fast, fluid and exciting team sport featuring two teams of six players (a goaltender and five skaters) on ice. It draws big crowds at the Olympic Games thanks to the drama and tension of the matches. Ice hockey originated in Canada in the early 19th century, based on several similar sports played in Europe');
insert into Sport (id, name, image_name, description) values (36,'Judo','jud', 'Judo is a Japanese martial art that focuses on throws and grappling techniques to subdue opponents, with an emphasis on physical fitness, mental discipline, and sportsmanship. Judo was invented by Jigoro Kano in Japan in 1882 as a safe and effective form of physical education and self-defence based on the principles of maximum efficiency and mutual benefit.');
insert into Sport (id, name, image_name, description) values (37,'Karate','kte', 'Karate is a Japanese martial art that uses striking techniques with hands, feet, elbows, and knees, as well as blocking and grappling, to develop physical and mental discipline. Karate is an ancient discipline with the roots of its current form originating on the Japanese island of Okinawa during the Ryukyu Dynasty, which was established in the 15th century.');
insert into Sport (id, name, image_name, description) values (38,'Luge','lug', 'Luge riders hurtle down a slippery ice track at great speed, relying on reflexes for steering. Unlike bobsleigh, however, they have no protection should they make an error. Luge is the French word for “sledge” and, like bobsleigh, it was developed as a sport in Switzerland. Its roots go back to the 16th century, but it was not until 300 years later that the first luge tracks were built by Swiss hotel owners to cater for thrill-seeking tourists.');
insert into Sport (id, name, image_name, description) values (39,'Marathon Swimming','ows', 'Marathon swimming sees athletes take on a 10km course in open water environments such as the sea, rivers and lakes - meaning it is as much a test of mental strength and tactical ability, as it is physical endurance. The open environment means that athletes must adjust to changing currents, while physical contact between competitors and water stops are a regular occurance. After approximately two hours of racing there is an exciting sprint finish in the final three kilometres.');
insert into Sport (id, name, image_name, description) values (40,'Modern Pentathlon','mpn', 'Modern Pentathlon comprises five different disciplines: swimming, fencing, horse riding (show jumping), pistol shooting and running. The original pentathlon - consisting of running, jumping, spear-throwing, discus and wrestling - was the climax of the Games in Ancient Greece. It held a position of unique importance with the winner ranked as Victor Ludorum.');
insert into Sport (id, name, image_name, description) values (41,'Nordic Combined','ncb', 'This sport, which has a long Olympic history, combines ski jumping and cross-country skiing. For centuries in the snow-covered North, skis were required to chase game and gather firewood in winter time. With long distances between the small, isolated communities, and hard, snowy winters, skiing also became important as means of keeping in social contact. The word “ski” is a Norwegian word which comes from the Old Norse word “skid”, a split length of wood.');
insert into Sport (id, name, image_name, description) values (42,'Rhythmic Gymnastics','gry', 'Olympic rhythmic gymnastics is a female-only event that uses apparatus to showcase skill, flexibility and musicality, and made its Olympic debut in Los Angeles for the 1984 Games. There are just two categories: individual all-around women and group all-around women. Find out everything you need to know about the sport in this video guide to rhythmic gymnastics. Rhythmic gymnastics originated in Europe during the 19th century and has since evolved into an Olympic sport.');
insert into Sport (id, name, image_name, description) values (43,'Rowing','row', 'Rowing involves propelling a boat using oars fixed to the vessel. It differs from other disciplines in that rowers sit with their backs to the direction of movement, therefore crossing the finish line backwards. In the Olympics, rowers race against each other as individuals or in crews of two, four or eight. Rowing was first used as a means of transport in ancient Egypt, Greece and Rome. As a sport, it probably began in England in the 17th and early 18th centuries, with the Oxford-Cambridge university boat race in the United Kingdom, which was inaugurated in 1828.');
insert into Sport (id, name, image_name, description) values (44,'Rugby Sevens','rug', 'Rugby sevens is the seven-a-side format of rugby union, which also includes a 15-a-side format. Legend has it that rugby union was invented during a football match in 1823 when a student at Rugby School in Great Britain called William Webb Elis picked up the ball in his hands and ran over the goal line.');
insert into Sport (id, name, image_name, description) values (45,'Sailing','sal', 'Formerly the world major form of long-distance trade and transport, sailing - the art of moving a boat or similar vessel by harnessing the waves and the wind - is now largely a sporting pursuit. Sailing has for thousands of years been a form of transport used in activities from exploration to fishing and even warfare.');
insert into Sport (id, name, image_name, description) values (46,'Shooting','sho', 'Sport shooting is the use of a firearm to hit a target with a bullet. These can be stationary targets or moving targets known as clays. Shooting as a sport has been practised for hundreds of years in European countries, with some German shooting clubs dating back more than 500 years.');
insert into Sport (id, name, image_name, description) values (47,'Short Track Speed Skating','stk', 'In short track speed skating, athletes compete not against the clock, but against each other. This introduces the elements of strategy, bravery and skill needed for racing. Short track (or indoor) speed skating began in Canada and the United States of America, where they held mass-start competitions on an oval track as early as 1905-1906. The lack of 400m long tracks led many North American skaters to practice on ice rinks. However, practicing on a smaller track brought new challenges, like tighter turns and shorter straightaways, which lead to different techniques in order to win on a shorter track. ');
insert into Sport (id, name, image_name, description) values (48,'Skateboarding','skb', 'Skateboarding is a sport and recreational activity that entails riding and performing tricks on a skateboard. Riders stand on a flat wooden board, comprised of a deck, truck and wheels, and a combination of momentum and footwork to execute tricks. Skateboarding first originated in 1950s California in the United States when surfers, looking for something to do when the waves were flat, attached roller skates to their boards.');
insert into Sport (id, name, image_name, description) values (49,'Skeleton','skn', 'Skeleton racing involves plummeting head-first down a steep and treacherous ice track on a tiny sled. It is considered the world first sliding sport. Sleighing is one of the oldest winter sports. Descriptions of the sport can be found in 16th-century literature, but as a racing sport, it can be traced to the mid-19th century, when British tourists started sliding down snowbound roads in the Alps. British and American holidaymakers built the first toboggan run in Davos in 1882.');
insert into Sport (id, name, image_name, description) values (50,'Ski Jumping','sjp', 'Over the past hundred years, ski jumping has evolved enormously, with different jumping techniques allowing jumpers to achieve even greater distances. The origin of ski jumping can be traced to Ole Rye, who jumped 9.5m in 1808. Norwegian Sondre Norheim is widely considered the father of modern ski jumping. In 1866, he won what has been described as the world’s first ski jumping competition with prizes, held at Ofte, Høydalsmo, Norway.');
insert into Sport (id, name, image_name, description) values (51,'Ski Mountaineering','smt', 'In ski mountaineering, often referred to as “skimo”, competitors ski uphill and downhill and use mountaineering abilities to race through snow-covered mountains. The first World Championships for ski mountaineering were held in 2002 in France and now this kind of international event is organised every two years alternatively with the Continental Championships. ');
insert into Sport (id, name, image_name, description) values (52,'Snowboard','sbd', 'Snowboarding combines elements of surfing, skateboarding and skiing. Snowboarding was developed in the United States in the 1960s as people across the country began to seek out new winter activities. Over the next decade, various pioneers boosted the production of boards, and the sport began to gain crossover appeal. Surfers and skateboarders became involved, and by 1980, snowboarding was a nationwide activity.');
insert into Sport (id, name, image_name, description) values (53,'Speed Skating','ssk', 'Speed skating began as a rapid form of transportation across frozen lakes and rivers. The Dutch were arguably the earliest pioneers of skating. They began using canals to maintain communication by skating from village to village as far back as the 13th century. Skating eventually spread across the channel to England, and soon the first clubs and artificial rinks began to form. Passionate skaters included several kings of England, Marie Antoinette, Napoleon III and German writer Johann Wolfgang von Goethe.');
insert into Sport (id, name, image_name, description) values (54,'Sport Climbing','clb', 'Sport Climbing is a modern discipline originated from traditional rock climbing. There are three different disciplines: boulder, lead and speed. In all of them, permanent anchors fixed to an artificial wall are used for climbing. In the early 1990s, it was decreed that international events would take place on purposely designed infrastructures only, leaving the natural environment without impact.');
insert into Sport (id, name, image_name, description) values (55,'Surfing','srf', 'Surfing is a water sport where an athlete performs manoeuvres on a wave while standing on a board. Surfing is believed to have been practised by fishermen in ancient times in Peru and later, in around 400 AD, across Polynesia. James King, who served under explorer Captain James Cook, wrote about surfing in Hawaii after Cook died in 1779. Prehistoric man learned to swim in order to cross rivers and lakes - we know this because cave paintings from the Stone Age depicting swimmers have been found in Egypt. Swimming was also referred to in Greek mythology.');
insert into Sport (id, name, image_name, description) values (56,'Swimming','swm', 'Swimming at the Olympics is both an individual and team sport where competitors propel their bodies through water in either an outdoor or indoor swimming pool using one of the following strokes: Freestyle, backstroke, breaststroke, or butterfly.');
insert into Sport (id, name, image_name, description) values (57,'Table Tennis','tte', 'Table tennis is a racket-and-ball sport played between two players or doubles teams, similar to tennis but on a table as its name suggests. It is thought that upper-class Victorians in England invented table tennis in the 1880s as a genteel, after-dinner alternative to lawn tennis, using whatever they could find as equipment. A line of books would often be the net, the rounded top of a champagne cork would be the ball and occasionally a cigar box lid would be a racket.');
insert into Sport (id, name, image_name, description) values (58,'Taekwondo','tkw', 'Taekwondo is a traditional Korean martial art practised in 206 countries. that teaches more than physical fighting skills. Taekwondo is a Korean word composed of three parts - Tae meaning foot or to step on, Kwon means to fist or fight and Do refers to the way or discipline. The origin of taekwondo dates back to Korea Three-Kingdom era (c.50 BC), when Shilla Dynasty warriors, the Hwarang, began to develop a martial art: Taekkyon ("foot-hand").');
insert into Sport (id, name, image_name, description) values (59,'Tennis','ten', 'The modern game is played in singles (one player versus another), doubles (teams of two) and mixed doubles (mixed-gender teams) and features differing scoring systems across international events. Tennis has a long history, but the birth of the game played today is thought to have taken place in England. The earliest recognisable relative to tennis, as we know it, was "jeu de paume", played in 11th century France. Played in a monastery courtyard, the game used the walls and sloping roofs as part of the court and the palm of the hand to hit the ball.');
insert into Sport (id, name, image_name, description) values (60,'Trampoline','gtr', 'Trampoline is a breathtaking sport that can see athletes bounce over 8 metres in the air while performing a series of complex twists and somersaults. As it is a highly technical sport, trampolinists are required to have an exceptional sense of balance and absolute precision. The first modern trampoline was built by George Nissen and Larry Griswold around 1934 at the University of Iowa. It was initially used to train tumblers and astronauts, and as a training tool to develop and hone acrobatic skills for other sports such as diving, gymnastics and freestyle skiing.');
insert into Sport (id, name, image_name, description) values (61,'Triathlon','tri', 'Triathlon is a multisport event that combines three disciplines: swimming, cycling and running. In triathlon, competitors compete in a race to the finish line with the first past the tape declared the winner. Triathlon was invented in the early 1970s by the San Diego Track Club in the USA as an alternative workout to the rigours of track training. The club first event consisted of a 10km run, an 8km cycle and a 500m swim.');
insert into Sport (id, name, image_name, description) values (62,'Volleyball','vvo', 'Volleyball is a sport played on a court by two teams of six players. The game was originally called “Mintonette”, a name derived from the game of badminton, because of its likeness to the sport. William G. Morgan, a YMCA physical education director and a student at Springfield College, is credited with creating the game of volleyball in 1895 in Holyoke, Massachusetts. Mintonette (as volleyball was called at the time) was designed to be an indoor pastime that could be enjoyed by older members of the YMCA, and took some of its characteristics from other sports including tennis and handball.');
insert into Sport (id, name, image_name, description) values (63,'Water Polo','wpo', 'Water polo is a sport played in water between two teams of seven players, including one goalkeeper, all wearing matching coloured caps. Players attempt to score goals by throwing the ball into the opposing teams goal, and the team with the most goals at the end of the game wins the match. The sport is typically played in a 3m deep pool measuring 30,6m by 20m for men and 25,6m by 20m for women, so that players cannot touch the bottom.');
insert into Sport (id, name, image_name, description) values (64,'Weightlifting','wlf', 'Weightlifting is a sport where athletes lift barbells loaded with weights. Weightlifting tests the strength, power and technique of athletes. Weightlifting has ancient origins. It was practised both by ancient Egyptian and Greek societies. It developed as an international sport primarily in the 19th century, and is one of the few sports to have featured at the first modern Olympic Games in Athens in 1896.');
insert into Sport (id, name, image_name, description) values (65,'Wrestling','wre', 'Wrestling is a sport where two individuals engage or grapple with the aim of throwing or holding their opponent’s shoulders to the ground, or else outscore them during the match. At the Olympics there are two variations of wrestling: Freestyle and Greco-Roman. The rules are almost identical, except that in Greco-Roman a wrestler may not attack an opponent below the waist or use his own legs to execute holds. With the possible exception of athletics, wrestling is recognised as the world’s oldest competitive sport.');
